name: 部署文档

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true

      - name: 设置 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: 安装依赖
        run: |
          corepack enable
          pnpm install --frozen-lockfile

      - name: 构建文档 (GitHub Pages)
        env:
          NODE_OPTIONS: --max_old_space_size=8192
          DEPLOY_TARGET: gh-pages
        run: |-
          pnpm run docs:build
          > src/.vuepress/dist/.nojekyll

      - name: 部署到 GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: src/.vuepress/dist

      # 重新构建用于服务器部署的版本
      - name: 构建文档 (服务器)
        env:
          NODE_OPTIONS: --max_old_space_size=8192
          DEPLOY_TARGET: server
        run: pnpm run docs:build

      - name: 部署到服务器
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: src/.vuepress/dist/
          remote_path: /opt/1panel/apps/openresty/openresty/www/sites/studyup.tech/index/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: deploy
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 执行部署后命令
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker exec 1Panel-openresty-063y nginx -s reload


